name: 'Example for Windows'

on: workflow_dispatch

jobs:
  # running simple jobs on default GitHub hosted Windows 11 runners (x64, arm64)
  test-x64:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [windows-latest, windows-11-arm]
    steps:
      - name: 'Run task (batch)'
        shell: cmd
        run: echo "Running arch=%PROCESSOR_ARCHITECTURE% runner_name=%RUNNER_NAME%, hostname=%COMPUTERNAME%"
      - name: 'Run task (powershell)'
        shell: pwsh
        run: Write-Output "Running arch=$env:PROCESSOR_ARCHITECTURE runner_name=$env:RUNNER_NAME on hostname=$env:COMPUTERNAME."
